[package]
name = "rust_glm"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
nalgebra = "0.33.2"
num-traits = "0.2.19"
rand = "0.8.0"
statrs = "0.18.0"
# newton = { path = "src/newton" }


