[package]
name = "rust_glm"
version = "0.1.0"
edition = "2024"

[dependencies]
nalgebra = "0.33.2"
polars = "0.47.1"
rand = "0.9.1"
rand_distr = "0.5.1"
statrs = "0.18.0"
newton = { path = "src/newton" }


